name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때만 동작

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t gorhkd/hello-docker:latest .

      - name: Push Docker Image to DockerHub
        run: docker push gorhkd/hello-docker:latest
